from enum import Enum

__author__ = 'basir'


class Features(Enum):
    SEQUENCE_PROFILE = 0
    POSITION_SPECIFIC_SCORING_MATRIX = 1
    POSITION_SPECIFIC_FREQUENCY_MATRIX = 2
    WINDOWED_POSITION_SPECIFIC_SCORING_MATRIX = 3
    WINDOWED_POSITION_SPECIFIC_FREQUENCY_MATRIX = 4
    D1_PLAIN_SHAPE_DISTRIBUTION = 5
    D1_SURFACE_SHAPE_DISTRIBUTION = 15
    D2_PLAIN_SHAPE_DISTRIBUTION = 6
    D2_SURFACE_SHAPE_DISTRIBUTION = 13
    D2_CATEGORY_SHAPE_DISTRIBUTION = 7
    SECONDARY_STRUCTURE = 8
    RELATIVE_ACCESSIBLE_SURFACE_AREA = 9
    ACCESSIBLE_SURFACE_AREA = 10
    PHI = 11
    PSI = 12
    NUMBER_OF_NEIGHBOURS = 14
    RESIDUE_DEPTH = 16
    HALF_SPHERE_EXPOSURE = 17
    RESIDUE_NEIGHBOURHOOD = 18
    B_VALUE = 19
    PROTRUSION_INDEX = 20