import inspect
import os

__author__ = 'basir'
pairpred_home = '/home/basir/Science/Research/PairPred/'
reports_directory = pairpred_home + 'writings/reports/'
data_directory = '../../../data/'
tools_directory = pairpred_home + 'tools/'
msms_home = tools_directory + 'msms/'
msms_exe = msms_home + 'msms'
msms_pdb2xyz = msms_home + 'pdb_to_xyzr'
dbd4_directory = pairpred_home + 'data/DBD4/'
pdb_directory = 'pdb/'
a_pdb_file = '1A2K_l_b.pdb'
unbound_sequence_directory = 'features/sequence/unbound/'
pickle_directory = 'pickle/'
dbd4_examples_file_prefix = 'dbd4-examples-'
dbd4_object_model_file_prefix = 'dbd4-object-model-'
dbd4_pair_file_prefix = 'pair_files/dbd4-pair-'
pssm_directory = 'features/pssm/'
wpssm_directory = 'features/wpssm/'
d2_directory = 'features/shape/d2/'
d1_directory = 'features/shape/d1/'
d2_category_directory = 'features/shape/d2_category/'
d1_category_directory = 'features/shape/d1_category/'
d2_surface_directory = 'features/shape/d2_surface/'
residue_depth_directory = 'features/depth/'
d1_surface_directory = 'features/shape/d1_surface/'
d1_surface_atoms_directory = 'features/shape/d1_atoms_surface/'
d2_surface_atoms_directory = 'features/shape/d2_atoms_surface/'
secondary_structure_directory = 'features/secondary/'
bound_secondary_structure_directory = 'features/secondary/bound'
stride_secondary_structure_directory = 'features/secondary_stride/'
half_sphere_exposure_directory = 'features/hse/'
b_factor_directory = 'features/b_factor/'
residue_neighbourhood_directory = 'features/residue_neighbourhood/'
protrusion_index_directory = 'features/protrusion_index/'
neighbourhood_threshold_key = 'n_threshold'
neighbourhood_sigma_key = 'n_sigma'
ss_abbreviations = 'HGIEBTC'
amino_acids = 'ACDEFGHIKLMNPQRSTVWY'
psaia_home = '/home/basir/Software/PSAIA-1.0'
psiblast_db_folder = '/home/basir/Software/ncbi-blast-2.2.30+/db'
psiblast_executable = '/home/basir/Software/ncbi-blast-2.2.30+/bin/psiblast'


def get_home_folder():
    return os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))